//
// Clouds.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Clouds: Codable {

    public var all: Int?

    public init(all: Int?) {
        self.all = all
    }


}

