//
// Forecast.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Forecast: Codable {

    public var list: [Info]?

    public init(list: [Info]?) {
        self.list = list
    }


}

