//
// Info.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Info: Codable {

    public var weather: [Weather]?
    public var main: Main?
    public var visibility: Int?
    public var wind: Wind?
    public var clouds: Clouds?
    public var dt: Int64?
    public var sys: Sys?
    public var name: String?

    public init(weather: [Weather]?, main: Main?, visibility: Int?, wind: Wind?, clouds: Clouds?, dt: Int64?, sys: Sys?, name: String?) {
        self.weather = weather
        self.main = main
        self.visibility = visibility
        self.wind = wind
        self.clouds = clouds
        self.dt = dt
        self.sys = sys
        self.name = name
    }


}

