//
// Sys.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Sys: Codable {

    public var type: Int?
    public var _id: Int?
    public var message: Double?
    public var country: String?
    public var sunrise: Int64?
    public var sunset: Int64?

    public init(type: Int?, _id: Int?, message: Double?, country: String?, sunrise: Int64?, sunset: Int64?) {
        self.type = type
        self._id = _id
        self.message = message
        self.country = country
        self.sunrise = sunrise
        self.sunset = sunset
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case message
        case country
        case sunrise
        case sunset
    }


}

