//
// Wind.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Wind: Codable {

    public var speed: Double?
    public var deg: Double?

    public init(speed: Double?, deg: Double?) {
        self.speed = speed
        self.deg = deg
    }


}

